# Project Details for SocioTechnical capital, employment and economic mobility
- subproject: "Environmental Sustainability, Socioeconomic Status and other Demographic Factors"
  description: "While much of the research in eco-feedback either implicitly or explicitly focuses on relatively affluent homeowners, there are many unique problems that arise when looking at low-income communities, tenants and landlords, and diverse cultural groups. Some our research projects have explored these issues."
  papers:

    - name: "Understanding factors of successful engagement around energy consumption between and among households"
      pic: cscw_228_thumb
      abstract: "In Proc. of CSCW 2014"
      authors: Dillahunt, T., Mankoff, J.
      mainlink: cscw_228
      resources:
        - type: pdf
          link: cscw_228


  # FIX LINK.....
  # UPDATE Environmental sustainability DESCRIPTION; ADD papers
    - name: "Deep Conservation in Urban India and its Implications for the Design of Conservation Technologies"
      pic: CHI-2013_thumb
      abstract: "Proceedings of the ACM 31st international conference on Human factors in computing systems, 2013, Paris, France "
      authors: Shrinivasan, Y., Jain, M., Seetharam, D., Choudhary, A., Huang, E., Dillahunt, T., Mankoff, J.
      mainlink: CHI-2013
      resources:
        - type: pdf
          link: CHI-2013

    - name: "Understanding Conflict Between Landlords and Tenants: Implications for Energy Sensing and Feedback"
      pic: fp134-dillahunt_thumb
      abstract: "In Proceedings of Ubicomp 2010, Copenhagen, Denmark"
      authors: T.Dillahunt, J. Mankoff, E. Paulos
      mainlink: fp134-dillahunt
      resources:
        - type: pdf
          link: fp134-dillahunt

    - name: "It’s Not All About Green: Energy Use in Low-Income Communities"
      pic: Low-Income_thumb
      abstract: "In Proceedings of Ubicomp 2009, Orlando, FL"  
      authors: T.Dillahunt, J. Mankoff, E. Paulos, S. Fussell
      mainlink: Low-Income
      resources:
        - type: pdf
          link: Low-Income

- subproject: "Footprints | Stepgreen"
  description: "The Footprints project leverages social networking to reduce individuals’ ecological footprints.  StepGreen is a website that allows individuals to commit to environmental sustainable behaviors and report when they make their commitments. Footprints is an umbrella project, which includes several investigations into ways to sense, detect, and motivate environmentally sustainable actions."
  papers:
    - name: "Stepgreen.org: Increasing Energy Saving Behaviours via Social Networks."
      pic: StepGreen_thumb
      abstract: "In Proceedings of the Fourth International AAAI Conference on Weblogs and Social Media 2010, Washington, D.C."
      authors: J. Mankoff, S. Fussell, T. Dillahunt, R. Glaves, C. Grevet, D. Matthews, H.S. Matthews, R. McGuire,  R. Thompson, A. Shick, L. Setlock.
      mainlink: StepGreen
      resources:
        - type: pdf
          link: StepGreen

    - name: "Ubigreen:  Investigating a Mobile Tool for Tracking and Supporting Green Transportation Habits"
      pic: UbiGreen_thumb
      abstract: "In Proceedings of Ubicomp 2009, Boston, MA"
      authors: J. Froehlich, T. Dillahunt, P. Klasnja, J. Mankoff, S. Consolvo, B. Harrison, J.A. Landay
      mainlink: UbiGreen
      resources:
        - type: pdf
          link: UbiGreen

    - name: "Tailoring Websites to Increase Contributions to Online Communities"
      pic: TailoringWebsites_thumb
      abstract: "CHI 2009, Extended abstracts, Boston, MA"
      authors: M.K. Lee, T. Dillahunt, B. Pendleton,  R. Kraut, S. Kiesler.
      mainlink: TailoringWebsites
      resources:
        - type: pdf
          link: TailoringWebsites

    - name: "Motivating environmentally sustainable behavior changes with a virtual polar bear"
      pic: PolarBear_thumb
      abstract: "Pervasive 2008 Workshop on Pervasive Persuasive Technology and Environmental Sustainability, Sydney, Australia"
      authors: T. Dillahunt, G. Becker, J. Mankoff,  and R. Kraut
      mainlink: PolarBear
      resources:
        - type: pdf
          link: PolarBear

# ADD THUMBNAILs (ALSO ADD WORKSHOP PAPERS HERE TOO!!)
- subproject: "Broader topics in sustainability"
  description: "We propose a framework for assessing the sustainability of interactive technologies. Our goal is to initiate steps towards a common standard of measurement for sustainability in the HCI community. This could help motivate green competition, raise consumer awareness, and acknowledge environmental leadership. In this paper we summarize our methodology, our results, and discuss how the framework can be integrated for testing within the HCI community."
  papers:
    - name: "Next steps for sustainable HCI"
      pic: p66-silberman_thumb
      abstract: "Interactions, September – October 2014"
      authors: "Silberman, M.S., Nathan, L., Knowles, B., Bendor, R., Clear, A., Håkansson, Dillahunt, T., Mankoff, J."
      mainlink: p66-silberman
      resources:
        - type: pdf
          link: p66-silberman

    - name: "Creating Resilient Communities for Post-Sustainable Times"
      pic: Dillahunt_postsustainability_v10_final_thumb
      abstract: "Proceedings of the 31st international conference on Human factors in computing systems, Post-Sustainability Workshop, 2013, Paris, France"
      authors: Dillahunt, T.
      mainlink: Dillahunt_postsustainability_v10_final
      resources:
        - type: pdf
          link: Dillahunt_postsustainability_v10_final

    - name: "A Proposed Framework for Assessing Environmental Sustainability in the HCI Community"
      pic: CHIWorkshopCFP_thumb
      abstract: "Accepted to the CHI Examining Appropriation, Re-use, and Maintenance Workshop at CHI 2010, Atlanta, GA"
      authors: "Tawanna Dillahunt, Jennifer Mankoff, Jodi Forlizzi"
      mainlink: CHIWorkshopCFP
      resources:
        - type: pdf
          link: CHIWorkshopCFP

